# One entry for each vulnerability group
[[IgnoredVulns]]
id = "GHSA-xx4v-prfh-6cgc"
reason = "Transitive dependency in eslint and vitest. Not part of distributed package."
[[IgnoredVulns]]
id = "GHSA-v6h2-p8h4-qcjw"
reason = "Transitive dependency in eslint and vitest. Not part of distributed package."
