// This file is auto-generated by kubernetes-fluent-client, do not edit manually
import { GenericKind, RegisterKind } from "kubernetes-fluent-client";
export class Datastore extends GenericKind {
  spec?: Spec;
}

export interface Spec {
  /**
   * The access modes for the datastore (e.g., ReadWriteOnce, ReadOnlyMany).
   */
  accessModes: string[];
  /**
   * The capacity of the datastore (e.g., 10Gi).
   */
  capacity: string;
  /**
   * The host path for the datastore storage.
   */
  hostPath: string;
  /**
   * The type of datastore. Allowed values: sqlite, valkey.
   */
  kind: Kind;
}

/**
 * The type of datastore. Allowed values: sqlite, valkey.
 */
export enum Kind {
  Sqlite = "sqlite",
  Valkey = "valkey",
}

RegisterKind(Datastore, {
  group: "pepr.io",
  version: "v1alpha1",
  kind: "Datastore",
  plural: "datastores",
});
