// This file is auto-generated by kubernetes-fluent-client, do not edit manually
import { GenericKind, RegisterKind } from "kubernetes-fluent-client";
export class Widget extends GenericKind {
  declare apiVersion?: string;
  declare kind?: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  declare metadata?: { [key: string]: any };
  spec?: Spec;
}

export interface Spec {
  name:      string;
  replicas?: number;
}

RegisterKind(Widget, {
  group: "example.com",
  version: "v1",
  kind: "Widget",
  plural: "widgets",
});