name: "Node.js CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
  merge_group:

permissions:
  contents: read

jobs:
  e2e:
    uses: "./.github/workflows/e2e.yml"
  format:
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Use Node.js latest
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: latest
          cache: npm

      - run: npm ci

      - name: Format check (changed files only)
        run: npm run format:check:changed

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 26]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test Unit
        run: npm test
